### ISSUE TITLE
Sharing constants

### ISSUE THREAD

**Issue by Vlad8161** [ayedo/ktsgenerator#3]
Hello. Is there any way to share constants between kotlin and typescript?

For example:

    object ApiConstants {
        const val SOME_VAL_1 = 1234
        const val SOME_VAL_2 = "hello world"
    }

UPD:
Expected TS output:

    let ApiConstants = {
        SOME_VAL_1: 1234,
        SOME_VAL_2: "hello world"
    }

**Comment by ayedo** [comment]
Hello, I'm not sure if it can do that. The plugin uses [ts-generator]( https://github.com/ntrrgc/ts-generator ) underneath, and probably supports whatever this plugin does. Maybe you can check out their site, and report back if it does, and you can't configure it in the plugin?
